version: "2"

services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=<022>
    volumes:
      - /home/docker/syncthing/config:/config
      - /home/docker/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
